"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/LIFX Menu.py']
DATA_FILES = [('images', ['images/lifx-icon@2x.png'])]
OPTIONS = {
	'plist': {
		'LSUIElement': True,
	}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
